---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod-maya-cluster
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/server-snippets: "gzip on;"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  name: litmuschaos-ingress
  namespace: litmuschaos-website
spec:
  rules:
  - host: litmuschaos.io
    http:
      paths:
      - backend:
          serviceName: production-litmuschaos-service
          servicePort: 80
        path: "/"
      - backend:
          serviceName: echoheaders
          servicePort: 80
        path: "/echo/"
  tls:
  - hosts:
    - litmuschaos.io
    secretName: litmuschaos-secrets-prod
