---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusdoc
  namespace: litmus-doc
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
    matchLabels:
      app: litmusdoc
  template:
    metadata:
      labels:
        app: litmusdoc
    spec:
      containers:
      - name: litmusdoc
        image: mayadataio/litmus-docs:master-9415dd
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mayadatasecret2
