apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-litmusdoc
  namespace: litmus-doc
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app : staging-litmusdoc
  template:
    metadata:
      labels:
        app : staging-litmusdoc
    spec:
      containers:
        - name: staging-litmusdoc
          image: bharamicrosystems/nginx:v2
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      # imagePullSecrets:
      # - name: mayadatasecret2
