apiVersion: v1
kind: Service
metadata:
  labels:
    app: prod-chart-litmuschaos
  name: prod-chart-litmuschaos-service
  namespace: litmus-hub
spec:
  ports:
  - name: prod-chart-litmuschaos
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: prod-chart-litmuschaos
